### ISSUE TITLE
Vehicle textures not loading

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#14]
Vehicle textures aren't loading after restart.

**Comment by micovery** [comment]
Looks like this defect is only present on v1_beta branch because AgentRev changed the variable name form "A3W_objectTexture" to "A3W_objectTextures" ... along with the contents.

**Comment by micovery** [comment]
This fix had not ended up in the Development_main branch for some reason. It's now there through d634b805d236117a298230ea4f95658c14c745f7
