### ISSUE TITLE
R3F not loading on saved vehicles.

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#20]
R3F isn't loading on saved vehicles after restart. I have a lock and unlock script so that fixes the ones that lock but all others wont tow or lift. I removed line 395-399 in vFunctions.sqf and that seemed to fix it.

**Comment by micovery** [comment]
Is this still a problem?

**Comment by IvanMMM** [comment]
Yes, I encountered this yesterday.It was purchased vehicle force-saved just before restart.

**Comment by Cael817** [comment]
I could reproduce this on the first try, "force-save" on a previously saved purchased vehicle and then restart the server (within 1 minute). Lock/unlock set the R3F options back. Vehicles that wasnt "force-saved" did have the R3F options. Used version extDB_beta_addons including 1408 commit.

**Comment by micovery** [comment]
Should be fixed by 15d08628a67aaed5dc0e1095441510d8059aa2ac, re-open if it's still an issue.
