### ISSUE TITLE
fn_setScore error

### ISSUE THREAD

**Issue by codexGW** [micovery/ArmA3_Wasteland.Altis#23]
I'm getting aerror when I rejoin my test server.

p_p>
 4:38:29   Error Undefined variable in expression: fn_setscore
 4:38:29 File mpmissions__CUR_MP.Altis\persistence\players\pFunctions.sqf, line 327
 4:38:29 "Restoring reviveCount = 0"
 4:38:29 Error in expression <, _value];

[player, _key, _value] call fn_setScore;
};} forEach _data;

};

p_p>
 4:38:29   Error position: <fn_setScore;
};} forEach _data;

};

**Comment by micovery** [comment]
Are you using the fork as-is, or did you merge it with another mission?

The error implies that you are missing the "fn_setScore" function which I added recently.

See:

https://github.com/micovery/ArmA3_Wasteland.Altis/commit/55ceac61325ee735837aa0de6982db6c476b7b6a
