### ISSUE TITLE
Loading locked vehicles

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#25]
Instead of defining which vehicles that are locked upon loading in the settings
A3W_locked_vehicles_list = [];
I suggest locking vehicles with "ownerUID" set to them or preferably (much preferred imho) restoring locks on vehicles that was saved locked (locked =>2).

This may not me necessary and im probably doing something wrong but as it is now mission vehicles load in locked also, anyway players should remember to lock em ;-)

**Comment by micovery** [comment]
Yap, this was to add a bit more granular control over which kinds of vehicles would be auto-locked after a restart.

I had feedback form another admin, where he did not want all kinds of vehicles auto-locked after a restart.  If you want all you want all types of vehicles to be auto-locked ... make:

```
A3W_locked_vehicles_list = ["Helicopter", "Plane", "Ship_F", "Car", "Motorcycle", "Tank"];
```

You can put this in the main_config.sqf of your wateland settings.

**Comment by Cael817** [comment]
Yep, i actually had it like that until i realized that the mission vehicles also locked, so i removed that and added (below the _cargo_repair) about line 197 or so...

 if (isSCALAR(_cargo_repair)) then {
    _obj setRepairCargo _cargo_repair;
  };
    //Cael817, SNAFU, If vehicle is owned by a player, lock it and make it untowable/unliftable.
    if (!isNil {_obj getVariable "ownerUID"}) then {
                //_veh setVariable ["R3F_LOG_disabled",true,true];
        _obj lock 2;
    }; 
 the "R3F_LOG_disabled" is already returned in the script (vFunctions.sqf) so its not needed here which seem to work fine. I would however like to only lock vehicles that where locked before the server restarted, thus in a way, punishing careless players =). Also my thought is that if the admins already allowed for some vehicles to be locked no extra settings would be necessary, then again the A3W_locked_vehicles_list isnt a bad idea, some vehicles dont really have locks ;-).

Anyway im very grateful for your work here, im using couchDB and it is very easy to work with.
