### ISSUE TITLE
Pull AI Action showing on UAVs

### ISSUE THREAD

**Issue by micovery** [micovery/ArmA3_Wasteland.Altis#35]
Even though it does not technically let you pull the UAV AI, it would be nice if it did not show.

**Comment by Cael817** [comment]
This seems to work.

va_pull_player_action_available = {
  if (not(cfg_va_pull_player_action_on)) exitWith {false};

  ARGVX3(0,_player,objNull);
  ARGVX3(1,_vehicle,objNull);
  ARGVX3(2,_target,objNull);

  if (not(alive _player)) exitWith {false};

  if (cursorTarget != _vehicle) exitWith {false};
  if (_vehicle isKindOf "UAV_02_base_F" or _vehicle isKindOf "UGV_01_base_F") exitWith {false};
  if (not(locked _vehicle < 2)) exitWith {false};
  if (not([_target, _vehicle] call va_player_inside)) exitWith {false};

  true
};

**Comment by Cael817** [comment]
sorry, "or" should probably be "||" ;-)

**Comment by micovery** [comment]
Can you send a pull request with this fix to the "Development_main_addons" branch. Also, to avoid unnecessary evaluation of conditions, you should wrap the check with { }  like this:

```
if (_vehicle isKindOf "UAV_02_base_F" ||  {_vehicle isKindOf "UGV_01_base_F"}) exitWith {false};
```
