### ISSUE TITLE
Undefined variable in "Storage"

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#51]
There seems to be an undefined variable in ps_functions.sqf, could be me doing something wrong thou but one of my admins reported the same issue.

12:25:39 Error in expression <box = [player, ps_container_class] call p_recreateStorageBox;

if (isNil "_box")>
12:25:39   Error position: <p_recreateStorageBox;

if (isNil "_box")>
12:25:39   Error Undefined variable in expression: p_recreatestoragebox
12:25:39 File mpmissions__CUR_MP.Altis\addons\storage\ps_functions.sqf, line 139

**Comment by micovery** [comment]
Hmm, I don't have that error. Which branch are you using? Also, verify in your RPT, that the following messages appear:

```
23:20:46 "pFunctions.sqf loading ..."
23:20:46 "pFunctions.sqf loading complete"
```

Sometimes, in SQF if there is some mismatched curly brace, or square bracket, it causes a file to not be fully parsed... without any errors or anything.

**Comment by Cael817** [comment]
Maybe my bad, i think i took down extDB_beta_addons up to 1426 commits, ill look again

**Comment by micovery** [comment]
Np, also check that you have this function:

https://github.com/micovery/ArmA3_Wasteland.Altis/blob/8124e03943adbb3a196c0815cd298c878e7d8a36/persistence/players/pFunctions.sqf#L408-L482

**Comment by Cael817** [comment]
Yup, that's it, i missed the update of that one. Sorry! Closing

Entirely my fault as in keep insisting on using ownerName instead of ownerN, think have to change my mind =). Wonder if spawnbeacons get both variables as they use ownerName in vanilla...
