### ISSUE TITLE
Vechical Flip 

### ISSUE THREAD

**Issue by lazerlee1990** [micovery/ArmA3_Wasteland.Altis#56]
User selects flip option in the scroll, they dont read the message and dont understand why its not flipping. 
They rage spam the options and the vechical resets muitple times and most likely ending in death.

**Comment by micovery** [comment]
Have to add a check to not spawn another unflip call if there is one already in progress.

**Comment by micovery** [comment]
Fixed by 4ee8e97bf400acaf707e47c7540d8b4eb0be565e.
