### ISSUE TITLE
Restore flying UAVs after restart.

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#60]
Restore flying UAVs to their flying "state" after restart.

Sorry for the short desc. just a reminder ;-)

**Comment by IvanMMM** [comment]
I think vehicles are not saving while in the air

**Comment by micovery** [comment]
The current implementation I think is that they are put on the ground if they are flying high enough. This works ok for helos most of the time but not for UAVs, and Jets, as it's unlikely that you'd be flying over a runway at the time of a restart.

**Comment by IvanMMM** [comment]
I think just skip saving it if it is in the air. In other way player must be saved/ restored inside vehicles and with connected uavs

**Comment by Cael817** [comment]
I dont think UAVs need to have a connected player, (jets are something else)
But in vanilla Rev adds  an AI and set a velocity, height and a waypoint for it. 
If they are to low cant "we" just add to the height they where saved at? lets say restore them with 1000m added to the height. And as it gets a speed set to them they shouldn't drop right?

Line 38 to 85 here looks perfect to me.
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/Development_main/persistence/server/world/vLoad.sqf

Why i think this is good is that i sometime have 2-3 UAVs in the air on the server and it gets kind of funny when they all try to land and if they would stay up players only have to reconnect after the restart, exact position, height and speed isnt that important, and if they dont log back on it would just run out of fuel.

But if its to much work it might not be worth it

**Comment by micovery** [comment]
The createVehicle command I believe has an option for creating a vehicle in-flight ... so that's not an issue. I don't know about the waypoint though. I can't just come up with a waypoint out of thin air :smile_cat:  ?  Maybe a few waypoints for the UAV to circle the map?

**Comment by Cael817** [comment]
Im guessing but it looks like Rev is using the position where the UAV was spawned, ie the saved position. That would actually make most sense... having it circle where it was saved.
                if (_flying) then
                {
                    _wp = (group _uav) addWaypoint [getPosATL _uav, 0];
                    _wp setWaypointType "MOVE";
                };

**Comment by micovery** [comment]
Fixed by 2156660357822f99bca02e7756f2747a24aea67e
