### ISSUE TITLE
Add mine saving

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#61]
Sorry for the short desc. just a reminder ;-)

**Comment by IvanMMM** [comment]
Did we break it:question:

**Comment by Cael817** [comment]
Nope... i might be wrong but i don't think its in any of micoverys branches, that why ;-)

**Comment by micovery** [comment]
Yah, a lot of those addons are in the a3armory GitHub... since it's just putting it here, I'll take any help I can get. Just send a pull request. I'll try to knock out a few from the list this weekend.

**Comment by Cael817** [comment]
Remember to take a break from this now and then, your work is much appreciated but there's really no hurry to add all this stuff in.

Thanks

**Comment by micovery** [comment]
Resolved by 32434b446105f35a3543a13bf351b99a7464740c. I pulled the commits from the A3Armory git. There might be some bug-fixes that were made after those commits that I could have missed. Do report if you see any missing bug-fixes.
