### ISSUE TITLE
Cannot pull pilot from helicopter

### ISSUE THREAD

**Issue by LouDnl** [micovery/ArmA3_Wasteland.Altis#69]
You cannot pull a pilot from a helicopter.

**Comment by micovery** [comment]
Please create 1 GitHub issue per defect.

**Comment by LouDnl** [comment]
Ok. But now I don't remember the other issue :)

**Comment by micovery** [comment]
It was for unflipping. There is already an existing issue for it.

**Comment by micovery** [comment]
Fixed by 910b13dd4a5d7e1e3992bdcbb6a36ea130d7d455
