### ISSUE TITLE
No config variable PDB_VehicleFileID

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#75]
Not sure this is an issue at all, if it is its extremely minor and probably not worth the work and should be put last on the list as its just informational =).

in the .rpt we get informational messages about the different file ids like this
0:57:33 "[INFO] config: PDB_PlayerFileID = A3W_"
20:57:33 "[INFO] config: PDB_ObjectFileID = A3W_"
20:57:33 "[INFO] config: PDB_MessagesFileID = A3W_"
20:57:33 "[INFO] config: PDB_AdminLogFileID = A3W_"
20:57:33 "[INFO] config: PDB_HackerLogFileID = A3W_"
20:57:33 "[INFO] config: PDB_PlayersListFileID = A3W_"

it seems that there is "PDB_VehicleFileID" missing, compared to the DB.

**Comment by micovery** [comment]
You are right, I missed that config ... it's using the same as objects for vehicles. I'll add one for it.

**Comment by micovery** [comment]
Fixed by 56940919845f25a6af0aebaa2f083c3a8f0c4210. If you were using a non-default value for `PDB_ObjectFileID`, then you will need to add the new `PBD_VehicleFileID` to your config. (specially if you are hosting multiple servers that are supposed to have separate vehicle documents)
