### ISSUE TITLE
readme.md still up to date?

### ISSUE THREAD

**Issue by randleman** [micovery/ArmA3_Wasteland.Altis#85]
I got some errors by using "npm install -g sock-rpc-stats" .
Node.js and sock.so worked fine.
Where i can find a step by step description?
I tried on Debian 7.8.0 x64

**Comment by IvanMMM** [comment]
What kind of errors exactly? People reporting that node 0.12 is working with errors, while old versions working fine.

**Comment by micovery** [comment]
hmm, yah, what are the errors? We'd probably have to update or remove, the mongodb dependency, as it seems to be the one that causes the most issues while installing, as it needs node-gyp.

**Comment by randleman** [comment]
indeed thats the issue :( my bad i installed 0.9.9
now i  tried with v0.10.32
seems to work so far
thanks guys ;)

EDIT: if i use your currently rep as .pbo  the client get "mission failed"
is there anything other to update?
i used all comments from the "readme.md"

**Comment by randleman** [comment]
thank you guys i had updated to latest release file and works pretty!
your persistence is an absolutely awesome work, well done!

**Comment by micovery** [comment]
The PBO from the instructions in the README is however out of date. You should build the PBO manually from the sources.
