### ISSUE TITLE
Possible issue with storage

### ISSUE THREAD

**Issue by Cael817** [micovery/ArmA3_Wasteland.Altis#86]
This may be intended but it seems that if you put a weapon with attachments in the storage the attachments disappear, at least after closing it. Is this by design? Need to do some further testing to see if this is a consistent thing or just some fluke.

**Comment by micovery** [comment]
It's because of an Arma 3 limitation. There is no way to get the list of weapon attachments for a weapon that is inside a box.

**Comment by Cael817** [comment]
OK, closing, was under the impression that this was a physical box spawned in somewhere and as "normal" boxes retain the attachments, sorry for the confusion

**Comment by micovery** [comment]
It is a physical box, but the box gets deleted as soon as you close the dialog, and recreated when you re-open the dialog.

**Comment by Cael817** [comment]
Ok, thanks for the explanation =)
